// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsuEcIGUM-B4LPZ1EC9oaN6Df5-9Fxbws',
    appId: '1:558845138750:web:f06b5d265a263428433e6f',
    messagingSenderId: '558845138750',
    projectId: 'mediplus-2eb83',
    authDomain: 'mediplus-2eb83.firebaseapp.com',
    storageBucket: 'mediplus-2eb83.appspot.com',
    measurementId: 'G-1YVDGNRXL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqdqE0kejnzbfromikpjH0Oekl6W7ePo8',
    appId: '1:558845138750:android:0825c38e58dcd3c3433e6f',
    messagingSenderId: '558845138750',
    projectId: 'mediplus-2eb83',
    storageBucket: 'mediplus-2eb83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwgkxDVHqSNLzO2bxjj_Z_CxTsQqWQqmU',
    appId: '1:558845138750:ios:8e2ba1c2b10cccec433e6f',
    messagingSenderId: '558845138750',
    projectId: 'mediplus-2eb83',
    storageBucket: 'mediplus-2eb83.appspot.com',
    iosBundleId: 'com.example.mediplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwgkxDVHqSNLzO2bxjj_Z_CxTsQqWQqmU',
    appId: '1:558845138750:ios:8e2ba1c2b10cccec433e6f',
    messagingSenderId: '558845138750',
    projectId: 'mediplus-2eb83',
    storageBucket: 'mediplus-2eb83.appspot.com',
    iosBundleId: 'com.example.mediplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsuEcIGUM-B4LPZ1EC9oaN6Df5-9Fxbws',
    appId: '1:558845138750:web:9fb4f1bbc73e0ebb433e6f',
    messagingSenderId: '558845138750',
    projectId: 'mediplus-2eb83',
    authDomain: 'mediplus-2eb83.firebaseapp.com',
    storageBucket: 'mediplus-2eb83.appspot.com',
    measurementId: 'G-14F48LH8EP',
  );
}
